### ISSUE TITLE
crash my mt server

### ISSUE THREAD

**Issue by Niklp09** [blert2112/lib_mount#3]
2021-11-14 17:40:43: WARNING[Server]: Deprecated call to get_look_yaw, use get_look_horizontal instead (at ...gger\minetest-5.4.1-win64\bin\..\mods\lib_mount\init.lua:274)
This error occurred a few thousand times in a few seconds. easy to fix.

change line 274 to:
			entity.object:set_yaw(entity.driver:get_look_**horizontal**() - rot_steer)

**Comment by blert2112** [comment]
Sorry. This was handed over to Panquesito7 ages ago and he has improved and updated many of my old mods. I no longer work on this stuff as my kids are not interested in Minetest anymore. One day I will clean out my github stuff.

https://github.com/Panquesito7/lib_mount

**Comment by blert2112** [comment]
oops, sorry. Thought this was on my old Fork. Shows how long I have been out of the loop. Reopening, lol.

**Comment by Panquesito7** [comment]
> 2021-11-14 17:40:43: WARNING[Server]: Deprecated call to get_look_yaw, use get_look_horizontal instead (at ...gger\minetest-5.4.1-win64\bin..\mods\lib_mount\init.lua:274) This error occurred a few thousand times in a few seconds. easy to fix.
> 
> change line 274 to: entity.object:set_yaw(entity.driver:get_look_**horizontal**() - rot_steer)

I tried doing that once in the past and it made the car move so weird, so I kept it as-is.
No idea how to fix that, though. Maybe @blert2112 knows. 🙂

**Comment by blert2112** [comment]
> > 2021-11-14 17:40:43: WARNING[Server]: Deprecated call to get_look_yaw, use get_look_horizontal instead (at ...gger\minetest-5.4.1-win64\bin..\mods\lib_mount\init.lua:274) This error occurred a few thousand times in a few seconds. easy to fix.
> > change line 274 to: entity.object:set_yaw(entity.driver:get_look_**horizontal**() - rot_steer)
> 
> I tried doing that once in the past and it made the car move so weird, so I kept it as-is. No idea how to fix that, though. Maybe @blert2112 knows. 🙂

Sorry, bro. I have not even looked at this code in years. As I said, my kids no longer play this game and they are why I started doing these mods. It would take a lot of time to get back into it and, TBH, I'm not interested either. Anyway, there are way more savy folks with their fingers in Minetest mods than me. Someone will come up with a fix.

**Comment by Panquesito7** [comment]
> > > 2021-11-14 17:40:43: WARNING[Server]: Deprecated call to get_look_yaw, use get_look_horizontal instead (at ...gger\minetest-5.4.1-win64\bin..\mods\lib_mount\init.lua:274) This error occurred a few thousand times in a few seconds. easy to fix.
> > > change line 274 to: entity.object:set_yaw(entity.driver:get_look_**horizontal**() - rot_steer)
> > 
> > 
> > I tried doing that once in the past and it made the car move so weird, so I kept it as-is. No idea how to fix that, though. Maybe @blert2112 knows. 🙂
> 
> Sorry, bro. I have not even looked at this code in years. As I said, my kids no longer play this game and they are why I started doing these mods. It would take a lot of time to get back into it and, TBH, I'm not interested either. Anyway, there are way more savy folks with their fingers in Minetest mods than me. Someone will come up with a fix.

All good! I can try to investigate further if required. Still, thanks for your support. 😄

**Comment by Lazerbeak12345** [comment]
(my bad, issues probably not related)

**Comment by Niklp09** [comment]
@Panquesito7 Did you make progress?

**Comment by Niklp09** [comment]
This is definitely not an enhancement it's a bug!

**Comment by Panquesito7** [comment]
Hey there! Sorry for the very very late reply.
Changing it to just `get_look_horizontal` won't work: the car will be in another direction.

I'm looking if there's a fix for this. Thanks for your patience. 🙂

**Comment by Panquesito7** [comment]
@Niklp09, should be fixed now. Please verify again if it works. Thanks. 🙂

**Comment by Niklp09** [comment]
haven't tested but fix LGTM
